### ISSUE TITLE
웹 페이지 제작

### ISSUE THREAD

**Issue by Overtakedio** [2021-SMHRD-IITP-Bigdata-4/soulful#5]
- [x] 메인페이지
- [ ] 장르별 구분 페이지
- [ ] 음악재생 전체화면 페이지 (가사)
- [x] 나만의 음악수집 (플레이리스트 , 플레이리스트음악, 가사모음집, 내 정보)
- [x] 회원가입
- [x] 로그인
- [ ] 플레이리스트 세부내용 출력
- [ ] 메인페이지 추천 내용 그래프

**Comment by Evlin97** [comment]
- [ ] 메인페이지
- [ ] 아티스트별 구분 페이지
- [ ] 장르별 구분 페이지
- [ ] Top 10
- [ ] 음악 재생 전체 화면 페이지 (가사)
- [ ] 플레이리스트 ,  플레이리스트음악, 가사모음집, 내정보
- [ ] 회원가입
- [ ] 로그인
- [ ] 플레이리스트 세부내용 출력

**Comment by Evlin97** [comment]
- [ ] 메인페이지
- [ ] 아티스트별 구분 페이지
- [ ] 장르별 구분 페이지
- [ ] 음원 Top 10
- [ ] 음악 재생 전체화면 페이지 (가사)
- [ ] 나만의 음악수집 (플레이리스트 , 플레이리스트음악, 가사모음, 내 정보)
- [ ] 회원가입
- [ ] 로그인
- [ ] 플레이리스트 세부 내용 출력
